# Generated by Django 5.0.4 on 2024-04-23 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helper',
            old_name='skils',
            new_name='skills',
        ),
    ]
